// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA60ycoIght9sr8SC-zbu2HQQGXf0zGU4U',
    appId: '1:106479145673:web:8760fbae769a16e178b318',
    messagingSenderId: '106479145673',
    projectId: 'study-d0aeb',
    authDomain: 'study-d0aeb.firebaseapp.com',
    storageBucket: 'study-d0aeb.firebasestorage.app',
    measurementId: 'G-KK7HQCMHT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8KlSiz4cOgKFioRPpxGFlBBxadbhlYxw',
    appId: '1:106479145673:android:b3742ad19e09107d78b318',
    messagingSenderId: '106479145673',
    projectId: 'study-d0aeb',
    storageBucket: 'study-d0aeb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIjtXFgiRL4uNylPFdeVz9XZGYthlZedA',
    appId: '1:106479145673:ios:10e5c77f3ee04c0578b318',
    messagingSenderId: '106479145673',
    projectId: 'study-d0aeb',
    storageBucket: 'study-d0aeb.firebasestorage.app',
    iosBundleId: 'com.example.study',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIjtXFgiRL4uNylPFdeVz9XZGYthlZedA',
    appId: '1:106479145673:ios:10e5c77f3ee04c0578b318',
    messagingSenderId: '106479145673',
    projectId: 'study-d0aeb',
    storageBucket: 'study-d0aeb.firebasestorage.app',
    iosBundleId: 'com.example.study',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA60ycoIght9sr8SC-zbu2HQQGXf0zGU4U',
    appId: '1:106479145673:web:562461ec57e62b8278b318',
    messagingSenderId: '106479145673',
    projectId: 'study-d0aeb',
    authDomain: 'study-d0aeb.firebaseapp.com',
    storageBucket: 'study-d0aeb.firebasestorage.app',
    measurementId: 'G-H5D6MB15L3',
  );
}
