name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout My Code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Flutter Version 3.29.0
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'

      - name: Install Dependencies
        run: flutter pub get

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.0" # Use a compatible Ruby version
          bundler-cache: true
          working-directory: android

      - name: Install Missing Gems
        working-directory: android
        run: |
          bundle add abbrev logger
          bundle install

      - name: Deploy to Firebase via Fastlane
        working-directory: android
        run: |
          bundle exec fastlane deploy_to_firebase

# name: Flutter CI/CD

# on:
#   push:
#     branches:
#       - main
      
     
#   pull_request:
#     branches:
#       - main
      

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout My Code 
#         uses: actions/checkout@v3

#       - name: Setup Java 17
#         uses: actions/setup-java@v3
#         with:
#           distribution: 'temurin' # Use the Eclipse Temurin distribution
#           java-version: '17'

#       - name: Install Flutter Version 3.29.0
#         uses: subosito/flutter-action@v2
#         with:
#           flutter-version: '3.29.0' # Use the required Flutter version

#       - name: Install Dependencies
#         run: flutter pub get


#       - name: Setup Ruby
#         uses: ruby/setup-ruby@v1
#         with:
#           ruby-version: "3.4.2"
#           bundler-cache: true
#           working-directory: android
 

#       # - name: Install Fastlane
#       #   run: gem install fastlane

#       - name: Deploy to Firebase via Fastlane
#         working-directory: android
        
   
        
#         run: |
#           bundle exec fastlane deploy_to_firebase
          
      
# name: Flutter CI/CD

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout My Code 
#         uses: actions/checkout@v3

#       - name: Setup Java 17
#         uses: actions/setup-java@v3
#         with:
#           distribution: 'temurin'
#           java-version: '17'

#       - name: Install Flutter Version 3.29.0
#         uses: subosito/flutter-action@v2
#         with:
#           flutter-version: '3.29.0'

#       - name: Install Dependencies
#         run: flutter pub get

#       - name: Setup Ruby
#         uses: ruby/setup-ruby@v1
#         with:
#           ruby-version: "3.5.0"
#           bundler-cache: true
#          # working-directory: android

#       - name: Install Fastlane
#         run: bundle install
#         working-directory: android



#       - name: Deploy to Firebase via Fastlane

#         run: bundle exec fastlane android deploy_to_firebase
#         # working-directory: android